require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Store::DetailsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Store::Detail. As you add validations to Store::Detail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Store::DetailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all store_details as @store_details" do
      detail = Store::Detail.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:store_details)).to eq([detail])
    end
  end

  describe "GET #show" do
    it "assigns the requested store_detail as @store_detail" do
      detail = Store::Detail.create! valid_attributes
      get :show, {:id => detail.to_param}, valid_session
      expect(assigns(:store_detail)).to eq(detail)
    end
  end

  describe "GET #new" do
    it "assigns a new store_detail as @store_detail" do
      get :new, {}, valid_session
      expect(assigns(:store_detail)).to be_a_new(Store::Detail)
    end
  end

  describe "GET #edit" do
    it "assigns the requested store_detail as @store_detail" do
      detail = Store::Detail.create! valid_attributes
      get :edit, {:id => detail.to_param}, valid_session
      expect(assigns(:store_detail)).to eq(detail)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Store::Detail" do
        expect {
          post :create, {:store_detail => valid_attributes}, valid_session
        }.to change(Store::Detail, :count).by(1)
      end

      it "assigns a newly created store_detail as @store_detail" do
        post :create, {:store_detail => valid_attributes}, valid_session
        expect(assigns(:store_detail)).to be_a(Store::Detail)
        expect(assigns(:store_detail)).to be_persisted
      end

      it "redirects to the created store_detail" do
        post :create, {:store_detail => valid_attributes}, valid_session
        expect(response).to redirect_to(Store::Detail.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved store_detail as @store_detail" do
        post :create, {:store_detail => invalid_attributes}, valid_session
        expect(assigns(:store_detail)).to be_a_new(Store::Detail)
      end

      it "re-renders the 'new' template" do
        post :create, {:store_detail => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested store_detail" do
        detail = Store::Detail.create! valid_attributes
        put :update, {:id => detail.to_param, :store_detail => new_attributes}, valid_session
        detail.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested store_detail as @store_detail" do
        detail = Store::Detail.create! valid_attributes
        put :update, {:id => detail.to_param, :store_detail => valid_attributes}, valid_session
        expect(assigns(:store_detail)).to eq(detail)
      end

      it "redirects to the store_detail" do
        detail = Store::Detail.create! valid_attributes
        put :update, {:id => detail.to_param, :store_detail => valid_attributes}, valid_session
        expect(response).to redirect_to(detail)
      end
    end

    context "with invalid params" do
      it "assigns the store_detail as @store_detail" do
        detail = Store::Detail.create! valid_attributes
        put :update, {:id => detail.to_param, :store_detail => invalid_attributes}, valid_session
        expect(assigns(:store_detail)).to eq(detail)
      end

      it "re-renders the 'edit' template" do
        detail = Store::Detail.create! valid_attributes
        put :update, {:id => detail.to_param, :store_detail => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested store_detail" do
      detail = Store::Detail.create! valid_attributes
      expect {
        delete :destroy, {:id => detail.to_param}, valid_session
      }.to change(Store::Detail, :count).by(-1)
    end

    it "redirects to the store_details list" do
      detail = Store::Detail.create! valid_attributes
      delete :destroy, {:id => detail.to_param}, valid_session
      expect(response).to redirect_to(store_details_url)
    end
  end

end
