# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  host: localhost
  database: helpdesk_development
  username: hd_Ruby
  password: Nero1234